<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <AssemblyName>RemoveMultiplayerPlayerLimit</AssemblyName>
    <TargetFramework>net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>annotations</Nullable>
    <LangVersion>12.0</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <PropertyGroup>
    <STS2Path Condition="$([MSBuild]::IsOSPlatform('Linux'))">$(HOME)/.local/share/Steam/steamapps/common/Slay the Spire 2</STS2Path>
    <STS2Path Condition="$([MSBuild]::IsOSPlatform('OSX'))">$(HOME)/Library/Application Support/Steam/steamapps/common/Slay the Spire 2</STS2Path>
    <STS2Path Condition="$([MSBuild]::IsOSPlatform('Windows'))">C:/Program Files (x86)/Steam/steamapps/common/Slay the Spire 2</STS2Path>

    <STS2DataPath Condition="$([MSBuild]::IsOSPlatform('Linux'))">$(STS2Path)/data_sts2_linuxbsd_x86_64</STS2DataPath>
    <STS2DataPath Condition="$([MSBuild]::IsOSPlatform('OSX'))">$(STS2Path)/data_sts2_macos_universal</STS2DataPath>
    <STS2DataPath Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(STS2Path)/data_sts2_windows_x86_64</STS2DataPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="build\**\*.cs" />
    <Compile Remove="references\**\*.cs" />
    <Compile Remove="tests\**\*.cs" />
    <Reference Include="sts2">
      <HintPath>$(STS2DataPath)/sts2.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GodotSharp">
      <HintPath>$(STS2DataPath)/GodotSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(STS2DataPath)/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Steamworks.NET">
      <HintPath>$(STS2DataPath)/Steamworks.NET.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
